-- Departments Table
CREATE TABLE DEPARTMENTS (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(100)
);

-- Employees Table
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(100),
    DEPT_ID NUMBER REFERENCES DEPARTMENTS(DEPT_ID),
    HIRE_DATE DATE,
    EMAIL VARCHAR2(100)
);

-- Attendance Table
CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
    ATTENDANCE_DATE DATE,
    CHECK_IN_TIME TIMESTAMP,
    CHECK_OUT_TIME TIMESTAMP,
    STATUS VARCHAR2(15) CHECK(STATUS IN ('PRESENT','ABSENT','ON LEAVE','HALF DAY')),
    CONSTRAINT UNIQUE_ATTENDANCE UNIQUE (EMPLOYEE_ID , ATTENDANCE_DATE)
);

-- Leave Requests Table
CREATE TABLE LEAVE_REQUESTS (
    LEAVE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
    START_DATE DATE,
    END_DATE DATE,
    LEAVE_TYPE VARCHAR2(20),
    STATUS VARCHAR2(20),
    REASON VARCHAR2(200)
);

-- Attendance Sequence
CREATE SEQUENCE ATTENDANCE_SEQ START WITH 1 INCREMENT BY 1;