-- Insert Departments
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES (1, 'Human Resources');
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES (2, 'IT');
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES (3, 'Finance');

-- Insert Employees
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, DEPT_ID, HIRE_DATE, EMAIL)
VALUES (101, 'Alice Johnson', 1, DATE '2022-03-01', 'alice@company.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, DEPT_ID, HIRE_DATE, EMAIL)
VALUES (102, 'Bob Smith', 2, DATE '2021-07-15', 'bob@company.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, DEPT_ID, HIRE_DATE, EMAIL)
VALUES (103, 'Charlie Patel', 2, DATE '2020-11-10', 'charlie@company.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, DEPT_ID, HIRE_DATE, EMAIL)
VALUES (104, 'Diana Rose', 3, DATE '2023-01-12', 'diana@company.com');

-- Initial Attendance
INSERT INTO ATTENDANCE (ATTENDANCE_ID, EMPLOYEE_ID, ATTENDANCE_DATE, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS)
VALUES (ATTENDANCE_SEQ.NEXTVAL, 101, DATE '2025-05-28', TO_TIMESTAMP('2025-05-28 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-28 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'PRESENT');

INSERT INTO ATTENDANCE (ATTENDANCE_ID, EMPLOYEE_ID, ATTENDANCE_DATE, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS)
VALUES (ATTENDANCE_SEQ.NEXTVAL, 102, DATE '2025-05-28', TO_TIMESTAMP('2025-05-28 09:15:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-28 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'PRESENT');

INSERT INTO ATTENDANCE (ATTENDANCE_ID, EMPLOYEE_ID, ATTENDANCE_DATE, STATUS)
VALUES (ATTENDANCE_SEQ.NEXTVAL, 103, DATE '2025-05-28', 'ABSENT');

-- Leave Requests
INSERT INTO LEAVE_REQUESTS (LEAVE_ID, EMPLOYEE_ID, START_DATE, END_DATE, LEAVE_TYPE, STATUS, REASON)
VALUES (1, 102, DATE '2025-05-29', DATE '2025-05-30', 'Sick', 'PENDING', 'Fever and cold');

INSERT INTO LEAVE_REQUESTS (LEAVE_ID, EMPLOYEE_ID, START_DATE, END_DATE, LEAVE_TYPE, STATUS, REASON)
VALUES (2, 103, DATE '2025-05-29', DATE '2025-05-30', 'Vacation', 'APPROVED', 'Family trip');